import { describe, expect, it } from 'vitest';
import type { ApifyClientLike } from '../../src/adapters/apify.js';
import {
  extractYoutubeVideoId,
  ingestYouTubeViaApify,
  transcriptFromApifyYoutubeRow,
} from '../../src/adapters/youtube.js';

describe('extractYoutubeVideoId', () => {
  it('parses watch, embed, shorts, live, and youtu.be', () => {
    expect(
      extractYoutubeVideoId('https://www.youtube.com/watch?v=dQw4w9WgXcQ'),
    ).toBe('dQw4w9WgXcQ');
    expect(extractYoutubeVideoId('https://youtu.be/dQw4w9WgXcQ')).toBe('dQw4w9WgXcQ');
    expect(
      extractYoutubeVideoId('https://www.youtube.com/embed/dQw4w9WgXcQ'),
    ).toBe('dQw4w9WgXcQ');
    expect(
      extractYoutubeVideoId('https://www.youtube.com/shorts/dQw4w9WgXcQ'),
    ).toBe('dQw4w9WgXcQ');
    expect(
      extractYoutubeVideoId('https://www.youtube.com/live/dQw4w9WgXcQ'),
    ).toBe('dQw4w9WgXcQ');
  });

  it('returns null for invalid URLs or ids', () => {
    expect(extractYoutubeVideoId('not-a-url')).toBeNull();
    expect(extractYoutubeVideoId('https://youtube.com/watch?v=short')).toBeNull();
  });
});

describe('transcriptFromApifyYoutubeRow', () => {
  it('maps subtitles array with start to segments', () => {
    const { textPlain, segments } = transcriptFromApifyYoutubeRow({
      subtitles: [
        { text: 'Hello', start: 0 },
        { text: 'World', startSeconds: 5 },
      ],
    });
    expect(textPlain).toBe('Hello\n\nWorld');
    expect(segments).toEqual([
      { startSec: 0, text: 'Hello' },
      { startSec: 5, text: 'World' },
    ]);
  });

  it('falls back to transcript string', () => {
    const { textPlain, segments } = transcriptFromApifyYoutubeRow({
      transcript: 'One block',
    });
    expect(textPlain).toBe('One block');
    expect(segments).toBeUndefined();
  });

  it('maps top-level segments (automation-lab / youtube-transcript style)', () => {
    const { textPlain, segments } = transcriptFromApifyYoutubeRow({
      segments: [
        { text: 'A', start: 0 },
        { text: 'B', start: 2 },
      ],
    });
    expect(textPlain).toBe('A\n\nB');
    expect(segments).toEqual([
      { startSec: 0, text: 'A' },
      { startSec: 2, text: 'B' },
    ]);
  });

  it('uses fullText when no segment arrays', () => {
    const { textPlain, segments } = transcriptFromApifyYoutubeRow({
      fullText: 'Merged only',
    });
    expect(textPlain).toBe('Merged only');
    expect(segments).toBeUndefined();
  });
});

describe('ingestYouTubeViaApify', () => {
  it('maps first dataset item to youtube bundle', async () => {
    let seenInput: Record<string, unknown> | undefined;
    const client: ApifyClientLike = {
      actor: () => ({
        call: async (input: Record<string, unknown>) => {
          seenInput = input;
          return { defaultDatasetId: 'ds1' };
        },
      }),
      dataset: () => ({
        listItems: async () => ({
          items: [
            {
              title: 'Demo',
              videoId: 'dQw4w9WgXcQ',
              subtitles: [{ text: 'Hi', start: 1.5 }],
            },
          ],
        }),
      }),
    };

    const bundle = await ingestYouTubeViaApify({
      url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
      actorId: 'test~actor',
      token: 'tok',
      client,
    });

    expect(bundle.source).toBe('youtube');
    expect(bundle.youtubeVideoId).toBe('dQw4w9WgXcQ');
    expect(bundle.canonicalUrl).toBe('https://www.youtube.com/watch?v=dQw4w9WgXcQ');
    expect(bundle.title).toBe('Demo');
    expect(bundle.textPlain).toBe('Hi');
    expect(bundle.transcriptSegments).toEqual([{ startSec: 1.5, text: 'Hi' }]);
    expect(bundle.fetchMethod).toBe('apify');
    expect(seenInput).toEqual({ startUrls: [{ url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ' }] });
  });

  it('uses urls input when youtubeInput is urls', async () => {
    let seenInput: Record<string, unknown> | undefined;
    const client: ApifyClientLike = {
      actor: () => ({
        call: async (input: Record<string, unknown>) => {
          seenInput = input;
          return { defaultDatasetId: 'ds1' };
        },
      }),
      dataset: () => ({
        listItems: async () => ({
          items: [
            {
              videoTitle: 'From store',
              videoId: 'dQw4w9WgXcQ',
              fullText: 'ok',
            },
          ],
        }),
      }),
    };

    await ingestYouTubeViaApify({
      url: 'https://youtu.be/dQw4w9WgXcQ',
      actorId: 'automation-lab/youtube-transcript',
      token: 'tok',
      youtubeInput: 'urls',
      client,
    });

    expect(seenInput).toMatchObject({
      urls: ['https://youtu.be/dQw4w9WgXcQ'],
      language: 'en',
      includeAutoGenerated: true,
      mergeSegments: true,
    });
  });

  it('throws when no transcript text', async () => {
    const client: ApifyClientLike = {
      actor: () => ({
        call: async () => ({ defaultDatasetId: 'ds1' }),
      }),
      dataset: () => ({
        listItems: async () => ({
          items: [{ title: 'Empty', videoId: 'dQw4w9WgXcQ' }],
        }),
      }),
    };

    await expect(
      ingestYouTubeViaApify({
        url: 'https://youtu.be/dQw4w9WgXcQ',
        actorId: 'test~actor',
        token: 'tok',
        client,
      }),
    ).rejects.toThrow(/no transcript/);
  });
});
