import { ApifyClient } from 'apify-client';
import { bundleFromParts } from '../normaliser.js';
import type { CaptureBundle, TranscriptSegment } from '../types/capture.js';
import type { ApifyClientLike } from './apify.js';

function defaultClient(token: string): ApifyClientLike {
  return new ApifyClient({ token }) as unknown as ApifyClientLike;
}

/** Supports watch, embed, shorts, live, and youtu.be links. */
export function extractYoutubeVideoId(urlString: string): string | null {
  try {
    const u = new URL(urlString);
    const h = u.hostname.replace(/^www\./, '').toLowerCase();
    if (h === 'youtu.be') {
      const id = u.pathname.split('/').filter(Boolean)[0] ?? '';
      return /^[\w-]{11}$/.test(id) ? id : null;
    }
    if (h === 'youtube.com' || h.endsWith('.youtube.com')) {
      const v = u.searchParams.get('v');
      if (v && /^[\w-]{11}$/.test(v)) return v;
      const embed = u.pathname.match(/\/embed\/([\w-]{11})/);
      if (embed) return embed[1]!;
      const shorts = u.pathname.match(/\/shorts\/([\w-]{11})/);
      if (shorts) return shorts[1]!;
      const live = u.pathname.match(/\/live\/([\w-]{11})/);
      if (live) return live[1]!;
    }
    return null;
  } catch {
    return null;
  }
}

function pickString(row: Record<string, unknown>, keys: string[]): string {
  for (const k of keys) {
    const v = row[k];
    if (typeof v === 'string' && v.trim()) return v.trim();
  }
  return '';
}

function numStart(o: Record<string, unknown>): number | undefined {
  for (const k of ['start', 'startSeconds', 'offset', 'time']) {
    const v = o[k];
    if (typeof v === 'number' && Number.isFinite(v)) return v;
    if (typeof v === 'string') {
      const n = parseFloat(v);
      if (!Number.isNaN(n)) return n;
    }
  }
  return undefined;
}

function textFromCaptionItem(item: unknown): string {
  if (typeof item === 'string') return item.trim();
  if (!item || typeof item !== 'object') return '';
  const o = item as Record<string, unknown>;
  const t =
    (typeof o.text === 'string' && o.text) ||
    (typeof o.subtitle === 'string' && o.subtitle) ||
    (typeof o.content === 'string' && o.content) ||
    '';
  return String(t).trim();
}

/**
 * Pull transcript text + optional segments from common Apify YouTube actor shapes.
 * Actors differ: try `subtitles`, `captions`, `transcript`, `text`, `description`, …
 */
export function transcriptFromApifyYoutubeRow(row: Record<string, unknown>): {
  textPlain: string;
  segments?: TranscriptSegment[];
} {
  const segments: TranscriptSegment[] = [];
  const arrays = [
    row.subtitles,
    row.captions,
    row.transcriptSegments,
    row.transcripts,
    row.segments,
  ];
  for (const arr of arrays) {
    if (!Array.isArray(arr)) continue;
    for (const item of arr) {
      const text = textFromCaptionItem(item);
      if (!text) continue;
      let startSec: number | undefined;
      if (item && typeof item === 'object') {
        startSec = numStart(item as Record<string, unknown>);
      }
      segments.push({ startSec, text });
    }
    if (segments.length > 0) break;
  }

  if (segments.length > 0) {
    return {
      textPlain: segments.map((s) => s.text).join('\n\n'),
      segments,
    };
  }

  const single =
    (typeof row.fullText === 'string' && row.fullText.trim()) ||
    (typeof row.transcript === 'string' && row.transcript.trim()) ||
    (typeof row.plainText === 'string' && row.plainText.trim()) ||
    pickString(row, ['text', 'markdown', 'description']);

  return { textPlain: single };
}

function videoIdFromRow(row: Record<string, unknown>, pageUrl: string): string | null {
  const fromUrl = extractYoutubeVideoId(pageUrl);
  if (fromUrl) return fromUrl;
  for (const k of ['videoId', 'id', 'youtubeId']) {
    const v = row[k];
    if (typeof v === 'string' && /^[\w-]{11}$/.test(v)) return v;
  }
  return null;
}

function apifyYoutubeActorInput(
  pageUrl: string,
  youtubeInput: 'start_urls' | 'urls' | undefined,
): Record<string, unknown> {
  if (youtubeInput === 'urls') {
    return {
      urls: [pageUrl],
      language: 'en',
      includeAutoGenerated: true,
      mergeSegments: true,
    };
  }
  return { startUrls: [{ url: pageUrl }] };
}

/**
 * Run your pinned **YouTube / transcript** Apify actor.
 * Input shape: `startUrls` (default) or `urls` — set `youtubeInput` in routing (see `routing.example.yaml`).
 *
 * Map the first dataset item to a bundle (`source: youtube`, transcript sections in writer).
 * Supports fields such as `segments[]`, `subtitles[]`, `fullText`, `transcript`, `videoTitle`, `thumbnail`.
 */
export async function ingestYouTubeViaApify(options: {
  url: string;
  actorId: string;
  token: string;
  build?: string;
  youtubeInput?: 'start_urls' | 'urls';
  client?: ApifyClientLike;
}): Promise<CaptureBundle> {
  const client = options.client ?? defaultClient(options.token);
  const input = apifyYoutubeActorInput(options.url, options.youtubeInput);
  const run = await client
    .actor(options.actorId)
    .call(input, options.build ? { build: options.build } : undefined);
  const { items } = await client.dataset(run.defaultDatasetId).listItems({ limit: 10 });
  const row = items[0] ?? {};

  const vid = videoIdFromRow(row, options.url);
  const canonicalUrl = vid
    ? `https://www.youtube.com/watch?v=${vid}`
    : new URL(options.url).href;

  const title =
    pickString(row, ['title', 'name', 'videoTitle']) ||
    (vid ? `YouTube ${vid}` : 'YouTube capture');

  const { textPlain, segments } = transcriptFromApifyYoutubeRow(row);
  if (!textPlain.trim()) {
    throw new Error(
      'youtube: Apify actor returned no transcript/text. Pin a YouTube transcript-capable actor and check dataset output fields.',
    );
  }

  const thumb =
    pickString(row, ['thumbnailUrl', 'thumbnail', 'thumbnailUrlHigh', 'coverUrl']) ||
    (typeof row.thumbnail === 'string' ? row.thumbnail : '');
  const images = thumb ? [{ url: thumb, alt: 'thumbnail' as const }] : [];

  return bundleFromParts({
    canonicalUrl,
    title,
    textPlain,
    images,
    fetchMethod: 'apify',
    source: 'youtube',
    youtubeVideoId: vid ?? undefined,
    transcriptSegments: segments,
  });
}
