"""YouTube + Apify transcript (mirror cli/src/adapters/youtube.ts)."""

from __future__ import annotations

import re
from typing import Any
from urllib.parse import parse_qs, urlparse

from apify_client import ApifyClient

from brain_api.normaliser import bundle_from_parts
from brain_api.types.capture import CaptureBundle, ImageRef, TranscriptSegment


def _id_ok(s: str) -> bool:
    return bool(re.match(r"^[\w-]{11}$", s))


def extract_youtube_video_id(url_string: str) -> str | None:
    try:
        u = urlparse(url_string)
        h = (u.hostname or "").replace("www.", "").lower()
        if h == "youtu.be":
            parts = [p for p in u.path.split("/") if p]
            id_ = parts[0] if parts else ""
            return id_ if len(id_) == 11 and _id_ok(id_) else None
        if h == "youtube.com" or h.endswith(".youtube.com"):
            v = parse_qs(u.query).get("v", [None])[0]
            if v and len(v) == 11 and _id_ok(v):
                return v
            for pattern in (r"/embed/([\w-]{11})", r"/shorts/([\w-]{11})", r"/live/([\w-]{11})"):
                m = re.search(pattern, u.path)
                if m and _id_ok(m.group(1)):
                    return m.group(1)
        return None
    except Exception:
        return None


def _pick_string(row: dict[str, Any], keys: list[str]) -> str:
    for k in keys:
        v = row.get(k)
        if isinstance(v, str) and v.strip():
            return v.strip()
    return ""


def _num_start(o: dict[str, Any]) -> float | None:
    for k in ("start", "startSeconds", "offset", "time"):
        v = o.get(k)
        if isinstance(v, (int, float)) and float(v) == float(v):
            return float(v)
        if isinstance(v, str):
            try:
                n = float(v)
                if n == n:
                    return n
            except ValueError:
                continue
    return None


def _text_from_caption_item(item: Any) -> str:
    if isinstance(item, str):
        return item.strip()
    if not item or not isinstance(item, dict):
        return ""
    t = (
        (item.get("text") if isinstance(item.get("text"), str) else "")
        or (item.get("subtitle") if isinstance(item.get("subtitle"), str) else "")
        or (item.get("content") if isinstance(item.get("content"), str) else "")
    )
    return str(t).strip()


def transcript_from_apify_youtube_row(row: dict[str, Any]) -> tuple[str, list[TranscriptSegment] | None]:
    segments: list[TranscriptSegment] = []
    arrays = [
        row.get("subtitles"),
        row.get("captions"),
        row.get("transcriptSegments"),
        row.get("transcripts"),
        row.get("segments"),
    ]
    for arr in arrays:
        if not isinstance(arr, list):
            continue
        for item in arr:
            text = _text_from_caption_item(item)
            if not text:
                continue
            start_sec: float | None = None
            if isinstance(item, dict):
                start_sec = _num_start(item)
            segments.append(TranscriptSegment(text=text, start_sec=start_sec))
        if segments:
            break

    if segments:
        text_plain = "\n\n".join(s.text for s in segments)
        return text_plain, segments

    single = ""
    for key in ("fullText", "transcript", "plainText"):
        v = row.get(key)
        if isinstance(v, str) and v.strip():
            single = v.strip()
            break
    if not single:
        single = _pick_string(row, ["text", "markdown", "description"])
    return single, None


def _video_id_from_row(row: dict[str, Any], page_url: str) -> str | None:
    from_url = extract_youtube_video_id(page_url)
    if from_url:
        return from_url
    for k in ("videoId", "id", "youtubeId"):
        v = row.get(k)
        if isinstance(v, str) and _id_ok(v):
            return v
    return None


def apify_youtube_actor_input(page_url: str, youtube_input: str | None) -> dict[str, Any]:
    if youtube_input == "urls":
        return {
            "urls": [page_url],
            "language": "en",
            "includeAutoGenerated": True,
            "mergeSegments": True,
        }
    return {"startUrls": [{"url": page_url}]}


def ingest_youtube_via_apify(
    *,
    url: str,
    actor_id: str,
    token: str,
    build: str | None = None,
    youtube_input: str | None = None,
    client: ApifyClient | None = None,
) -> CaptureBundle:
    c = client or ApifyClient(token)
    run_input = apify_youtube_actor_input(url, youtube_input)
    call_kw: dict[str, Any] = {"run_input": run_input}
    if build:
        call_kw["build"] = build
    run = c.actor(actor_id).call(**call_kw)
    if not isinstance(run, dict) or not run:
        raise RuntimeError("youtube: Apify actor call returned no run")
    ds_id = run.get("defaultDatasetId")
    if not ds_id:
        raise RuntimeError("youtube: Apify run missing defaultDatasetId")
    page = c.dataset(str(ds_id)).list_items(limit=10)
    items = list(getattr(page, "items", []) or [])
    row: dict[str, Any] = items[0] if items else {}

    vid = _video_id_from_row(row, url)
    canonical = f"https://www.youtube.com/watch?v={vid}" if vid else url

    title = (
        _pick_string(row, ["title", "name", "videoTitle"])
        or (f"YouTube {vid}" if vid else "YouTube capture")
    )

    text_plain, segments = transcript_from_apify_youtube_row(row)
    if not text_plain.strip():
        raise RuntimeError(
            "youtube: Apify actor returned no transcript/text. Pin a YouTube transcript-capable actor "
            "and check dataset output fields.",
        )

    thumb = (
        _pick_string(row, ["thumbnailUrl", "thumbnail", "thumbnailUrlHigh", "coverUrl"])
        or (row.get("thumbnail") if isinstance(row.get("thumbnail"), str) else "")
    )
    images = [ImageRef(url=thumb, alt="thumbnail")] if thumb else []

    return bundle_from_parts(
        canonical_url=canonical,
        title=title,
        text_plain=text_plain,
        images=images,
        fetch_method="apify",
        source="youtube",
        youtube_video_id=vid,
        transcript_segments=segments,
    )
